pipeline {

    agent any

   tools {

        maven 'LocalMaven'

        jdk 'Localjava'

    }

    stages {

        stage('Build Application') {

            steps {

                sh 'mvn -f java-tomcat-sample/pom.xml clean package'

            }

            post {

                success {

                    echo "Now Archiving the Artifacts...."

                    archiveArtifacts artifacts: '**/*.war'

                }

            }

        }

        stage('Deploy in Staging Environment'){

            steps{

                build job: 'Deploy to INT ENV'



            }

           

        }

        stage('Deploy to Production'){

            steps{

                timeout(time:5, unit:'DAYS'){

                    input message:'Approve PRODUCTION Deployment?'

                }

                build job: 'Deploy to PROD ENV'

            }

        }

    }

}
